---
- name: install neovim macos
  hosts: macos
  roles:
  - neovim
  - tmux
  - lazyvim

# - name: install neovim linux
#   hosts: linux
#   become: true # sudo privileges
#   roles:
#   - neovim
#   - tmux
#   - lazyvim
