---
- name: install neovim macos
  hosts: macos
  roles:
  - neovim
  - tmux
  - lazyvim
  - tmux-config

- name: install neovim linux
  hosts: linux
  roles:
    - neovim
    - tmux
    - lazyvim
    # - tmux-config
