---
# tasks file for tmux
- name: Install Tmux on macOS
  community.general.homebrew:
    name: tmux
    state: present
    update_homebrew: true
  when: ansible_os_family == "Darwin"

- name: Install Neovim on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Tmux
      ansible.builtin.apt:
        name: tmux
        state: present
#
# - name: Install Tmux on CentOS/RHEL
#   ansible.builtin.dnf:
#     name: tmux
#     state: present
#   when: ansible_os_family == "RedHat"
#
# - name: Install Tmux on Arch Linux
#   community.general.pacman:
#     name: tmux
#     state: present
#   when: ansible_distribution == "Archlinux"

- name: Check Tmux installation
  block:
    - name: Verify installation
      ansible.builtin.command: tmux -V
      register: tmux_version
      changed_when: false
      failed_when: tmux_version.rc != 0

    - name: Display Tmux version
      ansible.builtin.debug:
        var: tmux_version.stdout_lines
